main: us.someteamname.CustomEnchantments.Core
name: CustomEnchants
version: 1.0
author: TestBench1
commands:
  soulenchanter:
    description: Open the Enchants Menu
  enchantedbook:
    description: Spawn in an enchanted book
  souls:
    description: Interact with the souls economy!