name: DungeonPlugin
version: 0.0.1
authors: [Javisel, MattiBoi, Primzeh]
main: com.minecraftpluginteam.dungeonplugin.PluginMain
api-version: 1.16
depend: [Multiverse-Core,Multiverse-NetherPortals,Multiverse-Portals,VoidGenerator]

